### ISSUE TITLE
OSX install fails if XQuartz is not installed

### ISSUE THREAD

**Issue by pwim** [rcairo/rcairo#36]
Awesome to see that you're checking if I have brew installed, and using it to install cairo. Cairo itself is dependent on XQuartz. Unfortunately you cannot install XQuartz through brew, and need to install it through https://xquartz.macosforge.org. When I did `brew install cairo myself`, I got 

```
cairo: Unsatisfied dependency: XQuartz 0.0.0
Homebrew does not package XQuartz. Installers may be found at:
  https://xquartz.macosforge.org
```

which was helpful at understanding what to do. When I first tried to install the gem though, I got the following error message:

```
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... no
checking for brew... yes
installing 'cairo' native package... failed
failed to run 'brew install cairo'.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/pm/.rvm/rubies/ruby-2.1.2/bin/ruby
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables

extconf failed, exit code 1
```

I didn't notice that the failure was from brew initially, as the `*** extconf.rb failed ***` and below output hides it. I suppose this is a rubygems thing though? 

Anyways, not such a big deal, and I was able to resolve this myself, so I'm reporting this mainly to make things Googleable incase someone runs into a similar issue.

**Comment by kou** [comment]
Thanks for your report!
You could show the failure details by looking mkmf.log as error message says. ("Check the mkmf.log file for more details.")

Anyway, I changed extconf.rb to show command execution result on failure. Now, you don't need to find mkmf.log. You can show details in error message.

**Comment by pwim** [comment]
:clap: Great work!

**Comment by zenspider** [comment]
@pwim try installing cairo via: `brew install --without-x11`.
