### ISSUE TITLE
Can't specify path of PDFSurface as Pathname object

### ISSUE THREAD

**Issue by scivola** [rcairo/rcairo#37]
The following script fails to create a valid PDF file.

```rb
require 'pathname'
require 'cairo'

surface = Cairo::PDFSurface.new Pathname("sample.pdf"), 100, 100
context = Cairo::Context.new surface

context.move_to 10, 10
context.line_to 90, 90
context.stroke

context.show_page

surface.finish
```

The content of sample.pdf is merely '%EOF'.

Why?

If we change the first argument of PDFSurface.new to String instead of Pathname, it is okay.

Pathname object has `write` method, but ...

Environment:
ruby 2.1.6p336 (2015-04-13 revision 50298) [i386-mingw32]
cairo (1.14.1 x86-mingw32)

**Comment by kou** [comment]
> Why?

Because `pathname.write(data)` equals to `IO.write(path.to_path, data)`. `IO.write` truncates and writes at offset 0 by default.

Anyway, I've added `Pathname` support. Thanks for your report.

**Comment by scivola** [comment]
Thank you!
