### ISSUE TITLE
An error occurred while installing cairo (1.14.1), and Bundler cannot continue. Make sure that `gem install cairo -v '1.14.1'` succeeds before bundling.

### ISSUE THREAD

**Issue by mallick7** [rcairo/rcairo#38]
can some one help me to resolve this issue: An error occurred while installing cairo (1.14.1), and Bundler cannot continue. Make sure that `gem install cairo -v '1.14.1'` succeeds before bundling.

currently i use mac 10.10.3 version, earlier in older OS version i was not having this issue.
<img width="1440" alt="screen shot 2015-07-21 at 18 56 13" src="https://cloud.githubusercontent.com/assets/11551588/8869367/514835ea-3200-11e5-9e51-50763089a47e.png">
<img width="1440" alt="screen shot 2015-07-21 at 19 18 35" src="https://cloud.githubusercontent.com/assets/11551588/8869370/57f9a4f0-3200-11e5-9559-170fe03065b1.png">
<img width="1440" alt="screen shot 2015-07-21 at 19 23 03" src="https://cloud.githubusercontent.com/assets/11551588/8869375/5c5b7bfe-3200-11e5-92db-77b7ba130334.png">

see screenshot

**Comment by kou** [comment]
Thanks for your report.
I don't have OS X. Could you help me?

I want you to try building the master on your OS X. Could you show me the result of the following command lines:

```text
% git clone https://github.com/rcairo/rcairo.git
% cd rcairo
% ruby extconf.rb
% make
```

**Comment by kou** [comment]
@yancya confirmed it. Thanks!!!

**Comment by yancya** [comment]
:innocent:

**Comment by mallick7** [comment]
still getting same error, see screenshot
<img width="1440" alt="screen shot 2015-07-27 at 20 39 59" src="https://cloud.githubusercontent.com/assets/11551588/8909623/f0ab808c-349f-11e5-9674-4a529f446ac3.png">

**Comment by mallick7** [comment]
@kou Could please reopen this issue. by considering above new screenshot.

**Comment by kou** [comment]
@mallick7 This problem isn't occurred in other OS X. It seems that your OS X is special. Could you provide your additional configurations/software for your OS X. If we find the cause of this problem, I'll reopen this issue. I will not reopen this issue without the information.

**Comment by mallick7** [comment]
@kou, the issue could be because one of these 4 

1. System Config: 
 System Version:	OS X 10.10.3 (14D136)
  Kernel Version:	Darwin 14.3.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal

2. Ruby version:
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.3.0]

3. Framework Gem dependences:

BAN7024:test_automation smallick$ cat Gemfile
source 'https://rubygems.org'
gem 'activesupport', "~> 3.2.8"
gem 'activemodel', "3.2.17"
gem 'activerecord', "3.2.17"
gem 'pg', '0.17.1'
gem 'columnize'
gem 'glib2', '2.2.5'
gem 'builder' , "3.0.4"
gem 'hoe'
gem 'selenium-webdriver'
gem 'watir-webdriver'
gem 'test-unit'
gem 'test-unit-runner-gtk2'
gem 'test-unit-full'
gem 'httpclient'
gem 'nokogiri'
gem 'lorax'
gem 'xmlrpcs'
gem 'zip'

4. RVM version: 
rvm 1.26.11 (latest)

**Comment by yancya** [comment]
```sh
$ RBENV_VERSION=1.9.3-p551 gem install cairo -v '1.14.1'                     
Fetching: cairo-1.14.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed cairo-1.14.1
1 gem installed
Installing ri documentation for cairo-1.14.1...
Building YARD (yri) index for cairo-1.14.1...
Installing RDoc documentation for cairo-1.14.1...
```

```sh
$ RBENV_VERSION=1.9.3-p551 ruby -v                      
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.4.0]
```

System Config
System Version: OS X 10.10.4 (14E46)
Kernel Version: Darwin 14.4.0
Boot Volume: Macintosh HD
Boot Mode: Normal

**Comment by mallick7** [comment]
please check you mail inbox , i have attached the video

**Comment by yancya** [comment]
Hmm. I watched your video. But I have no idea yet. :weary:

**Comment by yancya** [comment]
@mallick7 By the way, What gcc version which you are using ?

```sh
$ gcc -v
```

**Comment by mallick7** [comment]
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by mallick7** [comment]
hey @yancya and @kou can you guys provide me , any sort of solution.

**Comment by kou** [comment]
How about reinstalling your Xcode?

**Comment by kou** [comment]
http://stackoverflow.com/questions/27976312/how-to-cope-with-non-gcc-compatible-code-in-os-x-yosemite-core-headers may help you.

**Comment by kou** [comment]
Paste (not screenshot) the output of `ruby -rrbconfig -rpp -e 'pp RbConfig::CONFIG'`.

**Comment by kou** [comment]
It seems that this is your problem not rcairo's problem.
See description by @hnakamur: https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=ja&ie=UTF8&prev=_t&rurl=translate.google.co.jp&sl=ja&tl=en&u=https://gist.github.com/hnakamur/d375e9142b99884f241a&usg=ALkJrhhH_2wYFryGIwcLMyYBMfHA3zrRlQ

**Comment by hnakamur** [comment]
@mallick7 In summary, please do one of the following:

* Use `rbenv` https://github.com/sstephenson/rbenv#homebrew-on-mac-os-x to install ruby 1.9.3-p551 instead of `rvm`.
* Reinstall ruby with `rvm uninstall 1.9.3-p551` and `rvm install 1.9.3-p551 --with-gcc=clang`.
* Modify system header files by hand (see: http://stackoverflow.com/a/28014302 ).

I tried the first two options and succeeded to run `gem install cairo` and build `rcairo`.
I did not tried the last option myself and I do not recoomend this option.

**Comment by mallick7** [comment]
thanks guys it was really helpful....
