### ISSUE TITLE
requesting write to buffer/memory

### ISSUE THREAD

**Issue by mrtibs2000** [rcairo/rcairo#42]
I'm might not know how to use Cairo/RCairo, but I wasn't able to determine a way to capture a surface to a byte array. I'm working with Rails, so it would impact performance pretty heavily to write files out to the disk, just to read them back. TIA.

**Comment by kou** [comment]
You can use `StringIO` as output. See also: https://github.com/rcairo/rcairo/blob/master/samples/text2.rb

**Comment by mrtibs2000** [comment]
Thanks for the tip. I tried something like this and it doesn't work (test.png is empty). Any idea what I'm doing wrong?
```
a = StringIO.new
@cr.target.write_to_png(a)
File.open('test.png', 'w') do |f|
    f.puts(a.read)
end
```

**Comment by kou** [comment]
Ah, sorry. I showed wrong sample...
The correct sample is here: https://github.com/rcairo/rcairo/blob/master/samples/scalable.rb

**Comment by mrtibs2000** [comment]
That worked. Thanks!
