### ISSUE TITLE
SVGSurface created with nil filename does not match Cairo behavior

### ISSUE THREAD

**Issue by andymeneely** [rcairo/rcairo#43]
The Cairo docs state that if you give an SVG surface [a null filename, then no file is created](https://www.cairographics.org/manual/cairo-SVG-Surfaces.html#cairo-svg-surface-create). But, in rcairo, this leads to a TypeError:

```ruby
Cairo::SVGSurface.new(nil, 100, 100)
```
...leads to...
```
TypeError: no implicit conversion of nil into String
```

**Comment by kou** [comment]
Good catch!
I've fixed it.
