### ISSUE TITLE
Current build for Windows has problems with ruby pango / ruby gnome2

### ISSUE THREAD

**Issue by jjgh** [rcairo/rcairo#44]
Could you guys provide a new gem build for Windows?

The current one has problems with ruby-gnome2: https://github.com/ruby-gnome2/ruby-gnome2/issues/960

which were fixed in rcairo 2.11.91 with https://github.com/rcairo/rcairo/commit/8017181a188c737fd57b2b6c101b17bcf070a3b0

Thanks a lot

**Comment by kou** [comment]
I've released a new version. Could you try it?

**Comment by jjgh** [comment]
Tested and working! :+1: ty

**Comment by kou** [comment]
Thanks for testing it.
