### ISSUE TITLE
On Windows: cannot load such file -- cairo.so (LoadError)

### ISSUE THREAD

**Issue by jjgh** [rcairo/rcairo#47]
On Windows 7 64: 

```
> ruby -v

Ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32] 

> gem install gtk3

Fetching: pkg-config-1.2.0.gem (100%)
Successfully installed pkg-config-1.2.0
Fetching: native-package-installer-1.0.0.gem (100%)
Successfully installed native-package-installer-1.0.0
Fetching: cairo-1.15.6-x64-mingw32.gem (100%)
Successfully installed cairo-1.15.6-x64-mingw32
Fetching: glib2-3.1.3-x64-mingw32.gem (100%)
Successfully installed glib2-3.1.3-x64-mingw32
Fetching: gobject-introspection-3.1.3-x64-mingw32.gem (100%)
Successfully installed gobject-introspection-3.1.3-x64-mingw32
Fetching: gio2-3.1.3-x64-mingw32.gem (100%)
Successfully installed gio2-3.1.3-x64-mingw32
Fetching: atk-3.1.3-x64-mingw32.gem (100%)
Successfully installed atk-3.1.3-x64-mingw32
Fetching: cairo-gobject-3.1.3-x64-mingw32.gem (100%)
Successfully installed cairo-gobject-3.1.3-x64-mingw32
Fetching: pango-3.1.3-x64-mingw32.gem (100%)
Successfully installed pango-3.1.3-x64-mingw32
Fetching: gdk_pixbuf2-3.1.3-x64-mingw32.gem (100%)
Successfully installed gdk_pixbuf2-3.1.3-x64-mingw32
Fetching: gdk3-3.1.3-x64-mingw32.gem (100%)
Successfully installed gdk3-3.1.3-x64-mingw32
Fetching: rsvg2-3.1.3-x64-mingw32.gem (100%)
Successfully installed rsvg2-3.1.3-x64-mingw32
Fetching: gtk3-3.1.3-x64-mingw32.gem (100%)
Successfully installed gtk3-3.1.3-x64-mingw32
13 gems installed

> ruby ruby-gnome-example.rb

C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- cairo.so (LoadError)
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cairo-1.15.6-x64-mingw32/lib/cairo.rb:48:in `rescue in <top (required)>'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cairo-1.15.6-x64-mingw32/lib/cairo.rb:44:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/glib2-3.1.3-x64-mingw32/lib/glib2.rb:112:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.3-x64-mingw32/lib/gobject-introspection.rb:17:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gtk3-3.1.3-x64-mingw32/lib/gtk3.rb:17:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from ruby-gnome-example.rb:1:in `<main>'
```

**Comment by kou** [comment]
Thanks for your report.
I've released cairo 1.15.7. Please try it.

**Comment by jjgh** [comment]
It works! 
Thanks for the super fast reply and fix! :)

**Comment by kou** [comment]
Thanks for confirming it.

**Comment by plurix** [comment]
After I've upgraded from Ruby 2.3 (Win7/x64, also Vista/32b - both mingw) to Ruby 2.4 - cairo stopped working (on both machines). I've done also a clean installation without installing MSYS2 - it's the same: cannot load "cairo.so'.
=============================================================
Microsoft Windows [Wersja 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Wszelkie prawa zastrzeżone.
C:\_sciagi>ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
C:\_sciagi>irb -v
irb 0.9.6(09/06/30)
C:\_sciagi>gem list
*** LOCAL GEMS ***
bigdecimal (default: 1.3.0)
did_you_mean (1.1.0)
io-console (default: 0.4.6)
json (default: 2.0.2)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.3)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
test-unit (3.2.3)
xmlrpc (0.2.1)
C:\_sciagi>gem install cairo
Fetching: pkg-config-1.2.3.gem (100%)
Successfully installed pkg-config-1.2.3
Fetching: native-package-installer-1.0.3.gem (100%)
Successfully installed native-package-installer-1.0.3
Fetching: cairo-1.15.8-x64-mingw32.gem (100%)
Successfully installed cairo-1.15.8-x64-mingw32
Parsing documentation for pkg-config-1.2.3
Installing ri documentation for pkg-config-1.2.3
Parsing documentation for native-package-installer-1.0.3
Installing ri documentation for native-package-installer-1.0.3
Parsing documentation for cairo-1.15.8-x64-mingw32
Installing ri documentation for cairo-1.15.8-x64-mingw32
Done installing documentation for pkg-config, native-package-installer, cairo af
ter 0 seconds
3 gems installed
C:\_sciagi>gem list
*** LOCAL GEMS ***
bigdecimal (default: 1.3.0)
cairo (1.15.8 x64-mingw32)
did_you_mean (1.1.0)
io-console (default: 0.4.6)
json (default: 2.0.2)
minitest (5.10.1)
native-package-installer (1.0.3)
net-telnet (0.1.1)
openssl (default: 2.0.3)
pkg-config (1.2.3)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
test-unit (3.2.3)
xmlrpc (0.2.1)
C:\_sciagi>irb
irb(main):001:0> require 'cairo'
LoadError: cannot load such file -- cairo.so
        from C:/_prog/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:
55:in `require'
        from C:/_prog/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:
55:in `require'
        from C:/_prog/Ruby24/lib/ruby/gems/2.4.0/gems/cairo-1.15.8-x64-mingw32/l
ib/cairo.rb:48:in `rescue in <top (required)>'
        from C:/_prog/Ruby24/lib/ruby/gems/2.4.0/gems/cairo-1.15.8-x64-mingw32/l
ib/cairo.rb:44:in `<top (required)>'
        from C:/_prog/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:
133:in `require'
        from C:/_prog/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:
133:in `rescue in require'
        from C:/_prog/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:
40:in `require'
        from (irb):1
        from C:/_prog/Ruby24/bin/irb.cmd:19:in `<main>'
irb(main):002:0>

**Comment by kou** [comment]
Thanks for your report. I've fixed and released a new version.

Please don't reuse existing closed issue. Please create a new issue instead.
