### ISSUE TITLE
name clash between cairo.rb and cairo.so

### ISSUE THREAD

**Issue by terceiro** [rcairo/rcairo#5]
When rcairo is installed without rubygems (e.g. ruby extconf.rb && make && make install), there is a name clash between cairo.rb and cairo.so:

  $ ruby -r cairo -e 'puts :ok'
  /usr/lib/ruby/vendor_ruby/1.8/i486-linux/cairo.so: uninitialized constant Cairo::Color (NameError)
  $ echo $?
  1

That happens because the directory in which cairo.so ends up comes first in $LOAD_PATH, so when a program does `require "cairo"` it will end up loading cairo.so instead of cairo.rb. The solution that several other packages use for this is to add a _ext suffix for the compiled extension, e.g. in cairo's case it would be cairo_ext.

**Comment by tonytonyjan** [comment]
FYI, actually, some gems such as pg, bcrypt, posix-spawn, kgio, etc all follow the _ext suffix convention.
