### ISSUE TITLE
Not working on Windows Ruby 2.5?

### ISSUE THREAD

**Issue by andymeneely** [rcairo/rcairo#52]
Using the RubyInstaller for 2.5.0 (https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.5.0-2/rubyinstaller-2.5.0-2-x64.exe), installing this gem:

```
cairo requires Ruby version < 2.5, >= 2.1. The current ruby version is 2.5.0.
```

But I have seen that rcairo 1.15.11 works on Linux with Ruby 2.5. Was this intentional?

I also noticed that https://rubygems.org/gems/cairo/versions/1.15.11-x64-mingw32 has < 2.5 specified.

**Comment by kou** [comment]
Thanks. I'll release a new version that supports 2.5 in a few days.

**Comment by andymeneely** [comment]
Great! Thanks.

**Comment by kou** [comment]
I've released a new version.
