### ISSUE TITLE
Incorrect value at Cairo::Color::RGB#to_s

### ISSUE THREAD

**Issue by spoolkitamura** [rcairo/rcairo#54]
For example, color :INDIGO is "#4B0082FF".
But rcairo shows "#4C0082FF" as below.
```
require 'cairo'

color = :INDIGO
p Cairo::Color.parse(color).to_s   # => "#4C0082FF"
```

In line number 108 of lib/cairo/color.rb, I would think it might be '.round' method, not '.ceil' method.
```
def to_s
  "#%02X%02X%02X%02X" % to_a.collect {|v| (v * 255).ceil}
end
```

**Comment by kou** [comment]
Can you create a pull request for this?
`floor` may be better than `round`. We should test against all colors in `cairo/colors.rb`.

**Comment by spoolkitamura** [comment]
If we use `floor`, value `b` of :INDIGO becomes 0x81 as below.
So I would think `round` is better than them.

I also will try to check against all colors.
```
require 'cairo'

color = :INDIGO

p "#%02X%02X%02X%02X" % Cairo::Color.parse(color).to_a.collect {|v| (v * 255).ceil}    # => "#4C0082FF"  NG
p "#%02X%02X%02X%02X" % Cairo::Color.parse(color).to_a.collect {|v| (v * 255).floor}   # => "#4C0081FF"  NG
p "#%02X%02X%02X%02X" % Cairo::Color.parse(color).to_a.collect {|v| (v * 255).round}   # => "#4B0082FF"  OK

p Cairo::Color.parse(color).to_a.collect {|v| (v * 255)}  # => [75.00000000000011, 0.0, 129.9999999999999, 255.0]

```
