### ISSUE TITLE
CMYK or grayscale PDF

### ISSUE THREAD

**Issue by scivola** [rcairo/rcairo#56]
For printing purpose, the color space of PDFs must be basically CMYK or grayscale.

Is it impossible to get a CMYK or grayscale PDF via improving rcairo?

**Comment by kou** [comment]
It's impossible because cairo doesn't support CMYK yet.

It seems that you can convert RGB PDF to CMYK PDF by Ghostscript: http://zeroset.mnim.org/2014/07/14/save-a-pdf-to-cmyk-with-inkscape/

**Comment by scivola** [comment]
Thank you for your suggestion.
Ghostscript can certainly change the color space, but it change the internal structure widely. It is my apprehension.

I hope Cairo graphics library to become able to treat grayscale directly in the future.

**Comment by kou** [comment]
We can work together with cairo developers for the future.
