### ISSUE TITLE
bundle install fail for Cairo on Mac-OX

### ISSUE THREAD

**Issue by akankshasaxena** [rcairo/rcairo#58]
I am running into this issue with almost all the version of cairo, getting below error:
/Users/akankshasaxena/.gem/ruby/2.6.4/gems/pkg-config-1.3.8/lib/pkg-config.rb:342:in `parse_pc': .pc for /usr/local/opt/libffi/lib/pkgconfig/libffi.pc doesn't exist. (RuntimeError)

Sharing my system configuration : 

$ ruby -v -r pp -r pkg-config -e 'pp PackageConfig.new("cairo").paths' 
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
["/usr/local/lib/pkgconfig",
 "/usr/local/opt/mysql-client/lib/pkgconfig",
 "/usr/local/opt/openssl@1.1/lib/pkgconfig",
 "/usr/local/opt/openssl/lib/pkgconfig",
 "/usr/local/opt/ncurses/lib/pkgconfig",
 "/usr/local/opt/libevent/lib/pkgconfig",
 "/usr/lib/pkgconfig",
 "/usr/local/lib/pkgconfig",
 "/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14",
 "/usr/local/lib/pkgconfig",
 "/usr/local/share/pkgconfig",
 "/usr/lib/pkgconfig"]

$ sw_vers -productVersion
10.14.6

$ brew --prefix  
/usr/local

$which pkg-config
/usr/local/bin/pkg-config

$brew list | grep pkg-config
pkg-config

$ brew info pkg-config
pkg-config: stable 0.29.2 (bottled)
Manage compile and link flags for libraries
https://freedesktop.org/wiki/Software/pkg-config/
/usr/local/Cellar/pkg-config/0.29.2 (11 files, 627.2KB) *
  Poured from bottle on 2019-09-26 at 11:37:24
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pkg-config.rb
==> Analytics
install: 101,680 (30 days), 311,328 (90 days), 1,364,201 (365 days)
install_on_request: 28,181 (30 days), 82,442 (90 days), 332,464 (365 days)
build_error: 0 (30 days)

$ brew --repository
/usr/local/Homebrew

$ ls -la /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig
total 0
drwxr-xr-x  15 akankshasaxena  admin  480 Sep 26 11:33 .
drwxr-xr-x  10 akankshasaxena  admin  320 Sep 26 11:33 ..
drwxr-xr-x   9 akankshasaxena  admin  288 Sep 26 11:33 10.10
drwxr-xr-x   9 akankshasaxena  admin  288 Sep 26 11:33 10.11
drwxr-xr-x   9 akankshasaxena  admin  288 Sep 26 11:33 10.12
drwxr-xr-x   9 akankshasaxena  admin  288 Sep 26 11:33 10.13
drwxr-xr-x   9 akankshasaxena  admin  288 Sep 26 11:33 10.14
drwxr-xr-x   9 akankshasaxena  admin  288 Sep 26 11:33 10.15
lrwxr-xr-x   1 akankshasaxena  admin    4 Sep 26 11:33 10.4 -> 10.5
drwxr-xr-x   5 akankshasaxena  admin  160 Sep 26 11:33 10.5
drwxr-xr-x   5 akankshasaxena  admin  160 Sep 26 11:33 10.6
drwxr-xr-x   5 akankshasaxena  admin  160 Sep 26 11:33 10.7
drwxr-xr-x   9 akankshasaxena  admin  288 Sep 26 11:33 10.8
drwxr-xr-x   9 akankshasaxena  admin  288 Sep 26 11:33 10.9
drwxr-xr-x   4 akankshasaxena  admin  128 Sep 26 11:33 fuse

$ . gem list pkg-config

*** LOCAL GEMS ***

pkg-config (1.3.8, 1.3.7)

$ ruby --version
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]

There is old issue which got resolved 2 years back - https://github.com/rcairo/rcairo/issues/49
similar thing is happening with me

**Comment by kou** [comment]
Thanks for your report.
pkg-config 1.3.9 will fix this.

https://github.com/ruby-gnome/pkg-config/issues/18

**Comment by akankshasaxena** [comment]
Great Thanks! This worked for me.
