### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by brodock** [rcairo/rcairo#62]
When looking at COPYING it looks like it's using Dual License (Ruby/GPL) which used to be the case for ruby https://en.wikipedia.org/wiki/Ruby_License. But when looking at gemspec it list only Ruby there.

If it's in fact dual license, I recommend you change your gemspec and list both: https://guides.rubygems.org/specification-reference/#licenses=

**Comment by kou** [comment]
My understanding that the (old) Ruby license means dual license of Ruby itself and GPL v2 or later. So I think that "Ruby" is enough.

Anyway, I've added "GPL-2.0-or-later".
