### ISSUE TITLE
Security Notice & Bug Bounty - NULL Pointer Dereference - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [rcairo/rcairo#64]
# Overview
[rcairo](https://rubygems.org/gems/cairo) is a Ruby bindings for cairo.

Affected versions of this package are vulnerable to NULL Pointer Dereference. `HarBuzz` is an OpenType text shaping engine, it contains a tool named `hb-view` which utilizes Cairo to give a graphical view of text using a font provided by the user. This vulnerability is due to logical problems in the program, and can cause a Denial of Service attack with a crafted font file.

# Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability and get rewarded 💰? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._

**Comment by kou** [comment]
It makes no sense.

**Comment by JamieSlome** [comment]
Thanks for letting us know - we have closed the bounty! 🍰
